// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuBtycR9Z8ajtI2zTBFwZUtUszR5mDggQ',
    appId: '1:1012599413510:web:b6b5fa2762ba5288235c87',
    messagingSenderId: '1012599413510',
    projectId: 'my-soul-sync',
    authDomain: 'my-soul-sync.firebaseapp.com',
    storageBucket: 'my-soul-sync.appspot.com',
    measurementId: 'G-CZVKRCXGN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvNxlcOfOUfKry_eoNbhKllEXZ2mtGM14',
    appId: '1:1012599413510:android:581836a572f54da0235c87',
    messagingSenderId: '1012599413510',
    projectId: 'my-soul-sync',
    storageBucket: 'my-soul-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMeLzlhvhjHDOUrlcV7fiGN8rYpzB4PSo',
    appId: '1:1012599413510:ios:f379f6e5b8251d97235c87',
    messagingSenderId: '1012599413510',
    projectId: 'my-soul-sync',
    storageBucket: 'my-soul-sync.appspot.com',
    iosBundleId: 'com.example.mySoulSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMeLzlhvhjHDOUrlcV7fiGN8rYpzB4PSo',
    appId: '1:1012599413510:ios:c481c94c80739837235c87',
    messagingSenderId: '1012599413510',
    projectId: 'my-soul-sync',
    storageBucket: 'my-soul-sync.appspot.com',
    iosBundleId: 'com.example.mySoulSync.RunnerTests',
  );
}
